var MSG = {
  title: "Code",
  blocks: "Blocks",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Run the program defined by the blocks in the workspace.",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard all blocks.",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Subroutines",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  BlockCozmoSay01: "I am Cozmo!",
  WorkspaceTabCamera: "Camera",
  WorkspaceTab3d: "3D",
  WorkspaceTabPython: "Python",
  WorkspaceTabXml: "XML",
  WorkspaceTabBlocks: "Blocks",
  WorkspaceTabConsole: "Console",
  WorkspaceDialogFormSaveCode01: "Open",
  WorkspaceDialogFormSaveCode02: "Save",
  WorkspaceDialogFormSaveCode03: "Cancel",
  WorkspaceDialogFormSaveCode04: "Are you sure you want to overwrite ",
  WorkspaceDialogFormSaveCode05: "Save code",
  WorkspaceDialogFormSaveCode06: "Filename:",
  catCozmoActuatorsBasic: "Basic activities",
  catCozmoActuatorsAdvanced: "Advanced Actions",
  catDevTools: "Coding tools",
  catCozmoSensors: "Sensors",
  catFunStuff: "Fun stuff",
 // Cozmo
  catCozmo: "Cozmo",
  catCozmoCubes: "Cozmo Cubes",
  catCozmoEvents: "Events",
  catCozmoUtils: "Macros",
// Thymio
  catThymioEvents: "Events"
};
