var MSG = {
  title: "Code",
  blocks: "Blocs",
  linkTooltip: "Sauvegarde et lien vers les blocs.",
  runTooltip: "Exécutez le programme défini par les blocs dans l'espace de travail.",
  badCode: "Erreur de programme:\n%1",
  timeout: "Le nombre maximal d'itérations d'exécution a été dépassé.",
  trashTooltip: "Supprimez tous les blocs.",
  catLogic: "Logique",
  catLoops: "Boucles",
  catMath: "Math",
  catText: "Texte",
  catLists: "Lists",
  catColour: "Couleur",
  catVariables: "Variables",
  catFunctions: "Sous-routine",
  listVariable: "liste",
  textVariable: "texte",
  httpRequestError: "Il y a eu un problème avec la demande.",
  linkAlert: "Partagez vos blocs avec ce lien:\n\n%1",
  hashError: "Désolé, \"%1\" ne correspond à aucun programme enregistré.",
  xmlError: "Impossible de charger votre fichier sauvegardé. Peut-être a-t-il été créé avec une version différente de Blockly?",
  badXml: "Erreur d'analyse XML:\n%1\n\nSélectionnez \"OK\" pour abandonner vos modifications ou \"Annuler\" pour continuer à modifier le XML.",
  BlockCozmoSay01: "Je suis Cozmo!",
  WorkspaceTabCamera: "Caméra",
  WorkspaceTab3d: "3D",
  WorkspaceTabPython: "Python",
  WorkspaceTabXml: "XML",
  WorkspaceTabBlocks: "Blocs",
  WorkspaceTabConsole: "Console",
  WorkspaceDialogFormSaveCode01: "Ouvrir",
  WorkspaceDialogFormSaveCode02: "Enregistrer",
  WorkspaceDialogFormSaveCode03: "Annuler",
  WorkspaceDialogFormSaveCode04: "Es-tu sûr de vouloir remplacer ",
  WorkspaceDialogFormSaveCode05: "Enregistrer le code",
  WorkspaceDialogFormSaveCode06: "Nom du fichier:",
  catCozmoActuatorsBasic: "Activités de base",
  catCozmoActuatorsAdvanced: "Activités avancées",
  catDevTools: "Outils de codage ",
  catCozmoSensors: "Capteurs",
  catFunStuff: "Choses sympas",
// Cozmo
  catCozmo: "Cozmo",
  catCozmoCubes: "Cozmo Cubes",
  catCozmoEvents: "Evénements",
  catCozmoUtils: "Macros",
// Thymio
  catThymioEvents: "Evénements"
};
