string target_bot   # COZMO, THYMIOII
string remote_ip    #
string code         # XML code
string action       # READY (0), RUN (1), STOP (2)
---
bool success        # True when registration is OK, otherwise false