string target_bot   # COZMO, THYMIOII
int64 debug_level   # 0 = off, 1 = debug code, 2 = load debuggable blockly js
string code         # code
---
bool success        # True when registration is OK, otherwise false